### ISSUE TITLE
KeyError: 'FrameRate_Mode'

### ISSUE THREAD

**Issue by chrisjohnson00** [chrisjohnson00/handbrake-k8s#104]
`python3 wrapper.py 'Pok'$'\303\251''mon - S03E16 - For Cryin'\'' Out Loud! WEBDL-1080p.mp4' 'Pok'$'\303\251''mon - S03E16 - For Cryin'\'' Out Loud! WEBDL-1080p.mp4'`

```
Traceback (most recent call last):
  File "//wrapper.py", line 131, in <module>
    main(arg_in_file_name, arg_out_file_name, arg_move_type)
  File "//wrapper.py", line 60, in main
    hpg.evaluate().render_profile('/tmp/generated.json')
  File "/handbrakeProfileGenerator/handbrake_profile_generator.py", line 81, in evaluate
    self.video_framerate_mode = self.mediainfo.get_video_frame_rate_mode()
  File "/mediainfo/mediainfo.py", line 104, in get_video_frame_rate_mode
    return first_track['FrameRate_Mode']
```

**Comment by chrisjohnson00** [comment]
```
mediainfo -f --Output=JSON /encode_in/Pokémon\ -\ S03E16\ -\ For\ Cryin\'\ Out\ Loud\!\ WEBDL-1080p.mp4 
{
"creatingLibrary": {
"name": "MediaInfoLib",
"version": "21.09",
"url": "https://mediaarea.net/MediaInfo"
},
"media": null
}
```
Looks like MediaInfo doesn't work with this file for some reason... why?

**Comment by chrisjohnson00** [comment]
After renaming the file, I get a proper output.

**Comment by chrisjohnson00** [comment]
Seems related to https://github.com/MediaArea/MediaInfo/issues/612
